language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r recipe *
  - mkdir -p deploy
  - mv recipe.zip deploy/recipe.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: recipe-service-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: recipe-service-bucket
    key: recipe.zip
    bundle_type: zip
    application: recipe-service # 웹콘솔에서 등록한 CodeDeploy애플리케이션
    deployment_group: recipe-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

# CI 실행 완료 시 이메일
notifications:
  email:
    recipients:
      - leejihun1024@gmail.com
